--- #YAML:1.0
name: Mail-Builder
version: 1.04
author:
  - Maroš Kollár <maros[at]k-1.com>
abstract: Easily create e-mails with attachments, html and inline images
license:             perl
distribution_type:   module
requires:
  MIME::Tools: 5.4
  Email::Valid: 0
  Class::Accessor: 0
  HTML::TreeBuilder: 3
  Mime::Types: 0
provides:
  Mail::Builder:
    file: lib/Mail/Builder.pm
    version: 1.03
  Mail::Builder::List:
    file: lib/Mail/Builder/List.pm
  Mail::Builder::Address:
    file: lib/Mail/Builder/Address.pm
  Mail::Builder::Image:
    file: lib/Mail/Builder/Image.pm
  Mail::Builder::Attachment:
    file: lib/Mail/Builder/Attachment.pm
build_requires:
  Test::Pod: 0
  Test::More: 0
  Test::Pod::Coverage: 0
urls:
  license: http://dev.perl.org/licenses/
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
resources:
  license: http://dev.perl.org/licenses/
generated_by: ExtUtils::ModuleMaker 0.49
