# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-Builder
version:      1.03
version_from: lib/Mail/Builder.pm
installdirs:  site
requires:
    Class::Accessor:               0
    Email::Valid:                  0
    HTML::TreeBuilder:             0
    MIME::Tools:                   0
    Test::More:                    0
    Test::Pod:                     0
    Test::Pod::Coverage:           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
