---
abstract: 'Easily create plaintext/html e-mail messages with attachments'
author:
  - 'Maroš Kollár'
build_requires:
  Test::Pod: 0
  Test::Pod::Coverage: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mail-Builder
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor: 0
  Email::MessageID: 0
  Email::Valid: 0
  Encode: 0
  HTML::TreeBuilder: 3.00
  IO::Lines: 0
  MIME::Tools: 5.4
  MIME::Types: 0
  Text::Table: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.120
